# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ./  # not important
train: relative_path_to/data/yolo_training_dataset/images/train
val: relative_path_to/data/yolo_training_dataset/images/val
test: relative_path_to/data/yolo_training_dataset/images/test # (optional)

names:
  0: ball
  1: referee
  2: goal_1
  3: goal_2
  4: player_1
  5: player_2